### ISSUE TITLE
Minor typo in readme

### ISSUE THREAD

**Issue by SelvamArul** [meliketoy/fine-tuning.pytorch#1]
Hi, 
Just a minor typo. In the requirements section, I guess you meant python2.7 and not PyTorch2.7. The link is redirecting to PyTorch website.

**Comment by bmsookim** [comment]
Hi, Thanks a lot for your comment :) What I meant was Pytorch for python 2.7. I realized that the script could be confusing, so I made some modifications.

**Comment by SelvamArul** [comment]
Thanks for fixing and for this very nice repo.
