### ISSUE TITLE
Clarification Needed

### ISSUE THREAD

**Issue by jfilter** [meliketoy/fine-tuning.pytorch#2]
Thanks for your great work. I think I am too unfamiliar with ML to understand some parts of the README. I would be very happy if you could help me out.

### 1.
Can you explain a little bit more what this means?

> data_base = [:dir to your original dataset]
> aug_base =  [:dir to your actually trained dataset]

What is the difference? Where should I put my data? Do I need to preprocess it myself?

### 2.
Are there any cases where you want to omit `--resetClassifier`? I though fine-tuning is all about resetting the classifier to a new task.

### 3.
What is `mean` and `std` in `config.py`. Are those the values for my own dataset? Do I have to compute them myself?

**Comment by bmsookim** [comment]
Hi,

Thanks for showing interest in my repository.

1.

You only need to put the data you want to fine tune at the data_base
repository (seperated by its class), then you could run the code in my
image_preprocessing repository.

The code will do the rest of the work :)

If you follow the link to my image preprocessing repository, you can see
further instructions.

2.

You're correct. There isn't any case omitting --resetClassifier is
required. That was just a style for showing that I'm performing fine-tuning
on a new dataset.

3.

If you follow the image_preprocessing repository, there is a menu that
automatically calculates the mean and std for you.

There is no need for calculating those variables yourself.


Hope this mail helps you through your data.

E-mail me if you have further questions, and thank you again for visiting
my GitHub.

Sincerely, Bumsoo Kim

2017-11-12 6:17 GMT+09:00 Johannes Filter <notifications@github.com>:

**Comment by jfilter** [comment]
Thanks mate!
