### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jfilter** [meliketoy/fine-tuning.pytorch#3]
Hey,

could you please add a license (e.g. MIT) to the repo? This would allow other people to build upon your work.

Kind Regards
Johannes

**Comment by bmsookim** [comment]
Hi, sorry for the late response.

This will be taken care of soon :)

**Comment by jfilter** [comment]
*ping*

**Comment by bmsookim** [comment]
Hi, sorry for the delay :(

I'm not sure it is correct, but I've added a license.

Thank you for your patience!

**Comment by jfilter** [comment]
No problem dude. ;) Thanks for adding it. The license is perfect as it is!
